import { Customer, Product, Challan, StockMovement, User } from '../types';

export const mockUsers: Record<string, User> = {
  'admin@nexora.demo': {
    id: 'usr-admin-01',
    name: 'Ravindra Kumar (Admin)',
    email: 'admin@nexora.demo',
    role: 'ADMIN',
  },
  'sales@nexora.demo': {
    id: 'usr-sales-01',
    name: 'Rohan Mehta (Sales Head)',
    email: 'sales@nexora.demo',
    role: 'SALES',
  },
  'warehouse@nexora.demo': {
    id: 'usr-warehouse-01',
    name: 'Vikram Singh (Warehouse Ops)',
    email: 'warehouse@nexora.demo',
    role: 'WAREHOUSE',
  },
  'accounts@nexora.demo': {
    id: 'usr-accounts-01',
    name: 'Pooja Iyer (Accounts Lead)',
    email: 'accounts@nexora.demo',
    role: 'ACCOUNTS',
  },
};

export const initialCustomers: Customer[] = [
  {
    id: 'cust-01',
    customerName: 'Rajesh Kulkarni',
    businessName: 'Apex Industrial Distributors Pvt Ltd',
    mobile: '+91 98201 45892',
    email: 'procurement@apexind.co.in',
    gstNumber: '27AABCA1234F1Z5',
    customerType: 'DISTRIBUTOR',
    address: 'Plot 42, MIDC Industrial Area, Andheri East, Mumbai, Maharashtra 400093',
    status: 'ACTIVE',
    followUpDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    notes: 'Key distributor for Western Region. High monthly volume.',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-02',
    customerName: 'Sunil Agarwal',
    businessName: 'Shreeram Agro & Hardware Supplies',
    mobile: '+91 98450 11223',
    email: 'sunil@shreeramagro.com',
    gstNumber: '29ABCDE5678G2Z1',
    customerType: 'WHOLESALE',
    address: '14/B Gandhi Bazaar, Hubballi, Karnataka 580020',
    status: 'ACTIVE',
    followUpDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    notes: 'Prefers bulk delivery on first Monday of every month.',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-03',
    customerName: 'Ananya Deshmukh',
    businessName: 'Metro Electricals & Automation',
    mobile: '+91 97654 32109',
    email: 'ananya.d@metroautomation.in',
    gstNumber: '27AABCM9876H1Z3',
    customerType: 'WHOLESALE',
    address: '88 Shivaji Nagar, Pune, Maharashtra 411005',
    status: 'ACTIVE',
    followUpDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    notes: 'Looking for distributor pricing on heavy duty relays.',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-04',
    customerName: 'Vikramaditya Roy',
    businessName: 'Bengal Solar & Renewable EPC',
    mobile: '+91 93310 98765',
    email: 'vroy@bengalsolar.org',
    gstNumber: '19AAACB4321J1Z8',
    customerType: 'DISTRIBUTOR',
    address: 'Sector V, Salt Lake City, Kolkata, West Bengal 700091',
    status: 'ACTIVE',
    followUpDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    notes: 'Quarterly supply contracts for MC4 connectors and surge protectors.',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-05',
    customerName: 'Karthik Ramanathan',
    businessName: 'Sri Balaji Motors & Spares',
    mobile: '+91 94440 55667',
    email: 'balajisparestn@gmail.com',
    gstNumber: '33AAAAA1234A1Z5',
    customerType: 'RETAIL',
    address: '102 Mount Road, Guindy, Chennai, Tamil Nadu 600032',
    status: 'ACTIVE',
    followUpDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    notes: 'Weekly cash-and-carry retail buyer.',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-06',
    customerName: 'Manpreet Singh Chadha',
    businessName: 'Chadha Toolcraft & Bearings',
    mobile: '+91 98140 77889',
    email: 'info@chadhatools.co.in',
    gstNumber: '03AAACC5678K1Z2',
    customerType: 'WHOLESALE',
    address: 'GT Road, Industrial Area B, Ludhiana, Punjab 141003',
    status: 'LEAD',
    followUpDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    notes: 'Requested product catalog and quote for carbide drill bits.',
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-07',
    customerName: 'Neha Singhal',
    businessName: 'Singhal Buildtech & Sanitaryware',
    mobile: '+91 98110 33445',
    email: 'neha@singhalbuildtech.com',
    gstNumber: '07AAACS9988L1Z9',
    customerType: 'RETAIL',
    address: '45 Chawri Bazar, Old Delhi, New Delhi 110006',
    status: 'LEAD',
    followUpDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    notes: 'Inquired regarding PVC pressure valves and fittings.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-08',
    customerName: 'Pradeep Chawla',
    businessName: 'Apex Machinery & Pumps Ltd',
    mobile: '+91 98250 88990',
    email: 'pchawla@apexpumps.com',
    gstNumber: '24AAACP4455M1Z1',
    customerType: 'DISTRIBUTOR',
    address: 'Plot 10, GIDC Estate, Vatva, Ahmedabad, Gujarat 382445',
    status: 'INACTIVE',
    followUpDate: null,
    notes: 'Account paused due to overdue payments in previous quarter.',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-01',
    productName: 'Heavy-Duty Industrial Motor 5HP 3-Phase',
    sku: 'MOT-IND-5HP-01',
    category: 'Motors & Actuators',
    unitPrice: 18500.0,
    currentStock: 14,
    minimumStock: 10,
    warehouseLocation: 'Bay A, Rack 01-A',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-02',
    productName: 'Variable Frequency Drive (VFD) 7.5kW',
    sku: 'VFD-IND-75KW',
    category: 'Electrical Automation',
    unitPrice: 24800.0,
    currentStock: 6,
    minimumStock: 8,
    warehouseLocation: 'Bay A, Rack 02-B',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-03',
    productName: 'Stainless Steel Ball Valve 2 Inch (SS 316)',
    sku: 'VAL-SS-BALL-2IN',
    category: 'Pipes & Valves',
    unitPrice: 3250.0,
    currentStock: 48,
    minimumStock: 25,
    warehouseLocation: 'Bay B, Rack 01-C',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-04',
    productName: 'High-Precision Digital Multimeter Pro',
    sku: 'TL-MM-PRO-09',
    category: 'Testing & Instruments',
    unitPrice: 4200.0,
    currentStock: 4,
    minimumStock: 15,
    warehouseLocation: 'Bay C, Shelf 04',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-05',
    productName: 'Solid State Relay 40A 240VAC',
    sku: 'REL-SSR-40A-240V',
    category: 'Electrical Automation',
    unitPrice: 850.0,
    currentStock: 120,
    minimumStock: 30,
    warehouseLocation: 'Bay A, Rack 03-A',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-06',
    productName: 'Cast Iron Submersible Pump 3HP',
    sku: 'PMP-SUB-3HP-CI',
    category: 'Pumps & Fluid Systems',
    unitPrice: 15200.0,
    currentStock: 2,
    minimumStock: 5,
    warehouseLocation: 'Bay D, Floor Area 02',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-07',
    productName: 'Industrial Safety Helmet with Visor (Pack of 10)',
    sku: 'PPE-HLM-VSR-10PK',
    category: 'Safety & PPE',
    unitPrice: 3500.0,
    currentStock: 35,
    minimumStock: 10,
    warehouseLocation: 'Bay C, Shelf 01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-08',
    productName: 'Pneumatic Solenoid Valve 5/2 Way 24VDC',
    sku: 'PNEU-VAL-52-24V',
    category: 'Pneumatics & Hydraulics',
    unitPrice: 1950.0,
    currentStock: 0,
    minimumStock: 12,
    warehouseLocation: 'Bay B, Rack 04-D',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialChallans: Challan[] = [
  {
    id: 'ch-01',
    challanNumber: 'CH-2026-00001',
    customerId: 'cust-01',
    status: 'CONFIRMED',
    totalQuantity: 6,
    totalAmount: 111000.0,
    notes: 'Urgent factory dispatch via V-Trans Logistics (Waybill: VT-88219)',
    createdBy: 'usr-admin-01',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    customer: initialCustomers[0],
    items: [
      {
        id: 'item-01',
        challanId: 'ch-01',
        productId: 'prod-01',
        productNameSnapshot: 'Heavy-Duty Industrial Motor 5HP 3-Phase',
        skuSnapshot: 'MOT-IND-5HP-01',
        unitPriceSnapshot: 18500.0,
        quantity: 6,
      },
    ],
  },
  {
    id: 'ch-02',
    challanNumber: 'CH-2026-00002',
    customerId: 'cust-02',
    status: 'CONFIRMED',
    totalQuantity: 20,
    totalAmount: 65000.0,
    notes: 'Monthly bulk hardware supply. Vehicle No: KA-25-EA-9012',
    createdBy: 'usr-sales-01',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    customer: initialCustomers[1],
    items: [
      {
        id: 'item-02',
        challanId: 'ch-02',
        productId: 'prod-03',
        productNameSnapshot: 'Stainless Steel Ball Valve 2 Inch (SS 316)',
        skuSnapshot: 'VAL-SS-BALL-2IN',
        unitPriceSnapshot: 3250.0,
        quantity: 20,
      },
    ],
  },
  {
    id: 'ch-03',
    challanNumber: 'CH-2026-00003',
    customerId: 'cust-03',
    status: 'DRAFT',
    totalQuantity: 25,
    totalAmount: 55250.0,
    notes: 'Quotation approved. Awaiting dispatch clearance from client accounts.',
    createdBy: 'usr-sales-01',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    customer: initialCustomers[2],
    items: [
      {
        id: 'item-03',
        challanId: 'ch-03',
        productId: 'prod-05',
        productNameSnapshot: 'Solid State Relay 40A 240VAC',
        skuSnapshot: 'REL-SSR-40A-240V',
        unitPriceSnapshot: 850.0,
        quantity: 25,
      },
      {
        id: 'item-04',
        challanId: 'ch-03',
        productId: 'prod-04',
        productNameSnapshot: 'High-Precision Digital Multimeter Pro',
        skuSnapshot: 'TL-MM-PRO-09',
        unitPriceSnapshot: 4200.0,
        quantity: 8,
      },
    ],
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'sm-01',
    productId: 'prod-01',
    quantity: 20,
    movementType: 'IN',
    reason: 'Purchase order receipt from OEM Supplier (PO-2026-440)',
    createdBy: 'usr-warehouse-01',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    product: initialProducts[0],
    user: { id: 'usr-warehouse-01', name: 'Vikram Singh (Warehouse Ops)', role: 'WAREHOUSE' },
  },
  {
    id: 'sm-02',
    productId: 'prod-01',
    quantity: 6,
    movementType: 'OUT',
    reason: 'Sales Challan confirmed: CH-2026-00001 dispatched to Apex Industrial Distributors',
    createdBy: 'usr-admin-01',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    product: initialProducts[0],
    user: { id: 'usr-admin-01', name: 'Ravindra Kumar (Admin)', role: 'ADMIN' },
  },
  {
    id: 'sm-03',
    productId: 'prod-03',
    quantity: 50,
    movementType: 'IN',
    reason: 'Batch import arrived from Pune foundry (INV-5512)',
    createdBy: 'usr-warehouse-01',
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    product: initialProducts[2],
    user: { id: 'usr-warehouse-01', name: 'Vikram Singh (Warehouse Ops)', role: 'WAREHOUSE' },
  },
  {
    id: 'sm-04',
    productId: 'prod-03',
    quantity: 20,
    movementType: 'OUT',
    reason: 'Sales Challan confirmed: CH-2026-00002 dispatched to Shreeram Agro & Hardware Supplies',
    createdBy: 'usr-sales-01',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    product: initialProducts[2],
    user: { id: 'usr-sales-01', name: 'Rohan Mehta (Sales Head)', role: 'SALES' },
  },
];
